alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: spookyemma.com
  type: PRIMARY
  zone: spookyemma.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: spookyemma-com
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: spookyemma-com
region: nyc
services:
- build_command: pnpm build
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${{ secrets.DATABASE_URL }}
  github:
    branch: main
    repo: emma-campbell/spookyemma.com
  http_port: ${{ secrets.DO_HTTP_PORT }}
  instance_count: ${{ secrets.DO_INSTANCE_COUNT }}
  instance_size_slug: ${{ secrets.DO_INSTANCE_SIZE_SLUG }}
  name: spookyemma-com
  run_command: yarn start
  source_dir: /
