name: Update App

on:
 push:
   branches: [main]

permissions:
  contents: read

jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       env:
           NEXT_PUBLIC_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
           NODE_ENV: production
       with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         app_name: spooky-web
         print_build_logs: true
         print_deploy_logs: true
        
